import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Design system from DESIGN.md
        primary: "#984063",
        "primary-container": "#DB779B",
        "on-primary": "#ffffff",
        "on-primary-container": "#5b0f33",
        "inverse-primary": "#ffb0c9",
        secondary: "#7D4E7B",
        "secondary-container": "#FDC2F7",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#7a4b78",
        tertiary: "#894681",
        "tertiary-container": "#C87DBC",
        "on-tertiary": "#ffffff",
        background: "#FFF8F8",
        "on-background": "#22191C",
        surface: "#FFF8F8",
        "surface-dim": "#e6d6d9",
        "surface-bright": "#fff8f8",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fff0f2",
        "surface-container": "#FAEAED",
        "surface-container-high": "#f4e4e7",
        "surface-container-highest": "#efdfe1",
        "on-surface": "#22191C",
        "on-surface-variant": "#534247",
        "inverse-surface": "#372e30",
        "inverse-on-surface": "#fdedf0",
        outline: "#867277",
        "outline-variant": "#d8c1c6",
        "surface-tint": "#984063",
        "surface-variant": "#EFDFE1",
        olive: "#A5A05A",
        "olive-light": "#e8e6c8",
        rose: "#DB779B",
        lilac: "#D9A1D4",
        plum: "#86437E",
        blush: "#F1C9CD",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "primary-fixed": "#ffd9e3",
        "primary-fixed-dim": "#ffb0c9",
      },
      fontFamily: {
        serif: ["Playfair Display", "Georgia", "serif"],
        sans: ["DM Sans", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "section-padding": "80px",
      },
      maxWidth: {
        container: "1120px",
      },
      backdropBlur: {
        xs: "4px",
        sm: "8px",
        DEFAULT: "12px",
        md: "16px",
        lg: "20px",
        xl: "24px",
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(134, 67, 126, 0.08)",
        "glass-lg": "0 16px 48px 0 rgba(134, 67, 126, 0.12)",
        "rose-glow": "0 0 40px rgba(219, 119, 155, 0.3)",
        "petal-shadow": "0 4px 16px rgba(152, 64, 99, 0.1)",
      },
      animation: {
        "petal-fall": "petalFall linear infinite",
        "fade-up": "fadeUp 0.8s ease forwards",
        "fade-in": "fadeIn 0.6s ease forwards",
        "shimmer": "shimmer 2s linear infinite",
        "float": "float 6s ease-in-out infinite",
        "pulse-rose": "pulseRose 3s ease-in-out infinite",
        "spin-slow": "spin 8s linear infinite",
      },
      keyframes: {
        petalFall: {
          "0%": { transform: "translateY(-10vh) rotate(0deg)", opacity: "0.8" },
          "100%": { transform: "translateY(110vh) rotate(720deg)", opacity: "0" },
        },
        fadeUp: {
          "0%": { opacity: "0", transform: "translateY(40px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% center" },
          "100%": { backgroundPosition: "200% center" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        pulseRose: {
          "0%, 100%": { boxShadow: "0 0 20px rgba(219, 119, 155, 0.2)" },
          "50%": { boxShadow: "0 0 40px rgba(219, 119, 155, 0.5)" },
        },
      },
      backgroundImage: {
        "gradient-blush": "linear-gradient(135deg, #FFF8F8 0%, #F1C9CD 30%, #D9A1D4 70%, #86437E 100%)",
        "gradient-rose": "linear-gradient(135deg, #DB779B 0%, #984063 100%)",
        "gradient-lavender": "linear-gradient(135deg, #D9A1D4 0%, #7D4E7B 100%)",
        "gradient-hero": "linear-gradient(160deg, #FFF8F8 0%, #faeaed 25%, #fdc2f7 60%, #DB779B 100%)",
        "gradient-section": "linear-gradient(180deg, #FFF8F8 0%, #faeaed 50%, #FFF8F8 100%)",
        "shimmer-gradient": "linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.6) 50%, transparent 100%)",
      },
    },
  },
  plugins: [],
};

export default config;
